# Custom SQL Server type for named instances
description=Microsoft SQL Server with custom connection
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
connectionSpec=jdbc:sqlserver://DESKTOP-0K6G6AH;instanceName=SQLRAFA;databaseName=ECommerceDemo;integratedSecurity=true;encrypt=true;trustServerCertificate=true
extends=mssql05
