# Custom SQL Server type for named instances
description=Microsoft SQL Server with custom connection
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
connectionSpec=jdbc:sqlserver://SRV033;instanceName=INTEGRACAO;databaseName=IPMSYSTEM_rafael_silva03;integratedSecurity=true;encrypt=true;trustServerCertificate=true
extends=mssql05
